from Interface.IExecutableEntity import *
from Interface.IBreeding import *
from Interface.IBreedable import *
from Interface.IDrawableEntity import *
from Interface.IComputeAndEvolvEntity import *
from Interface.IImmortal import *
from Interface.ISpatial import *
from Interface.ICommunity import *
from Interface.ITypeLifeCycleStages import *
from Interface.IMortal import *
from Interface.IPositioning import *
from Interface.ISpatialProperties import *
from Interface.IMoving import *
from Interface.IEat import *
from Interface.IEnergy import *
from Interface.IAwareness import *
